"""202601301756

Revision ID: c48592ca96aa
Revises: 
Create Date: 2026-01-30 17:56:29.028362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c48592ca96aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('position-name'))

    op.drop_table('t_position')
    op.drop_table('t_user_role')
    op.drop_table('t_media_tag')
    op.drop_table('t_dict')
    op.drop_table('t_role_menu')
    with op.batch_alter_table('t_role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('1'))

    op.drop_table('t_role')
    op.drop_table('t_episodes')
    op.drop_table('t_menu')
    with op.batch_alter_table('t_user_product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('index_product_id'))
        batch_op.drop_index(batch_op.f('index_source_type'))
        batch_op.drop_index(batch_op.f('index_user_id'))
        batch_op.drop_index(batch_op.f('index_user_product'))

    op.drop_table('t_user_product')
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_name'))

    op.drop_table('t_user')
    with op.batch_alter_table('t_org', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('org_name'))
        batch_op.drop_index(batch_op.f('parentid'))

    op.drop_table('t_org')
    with op.batch_alter_table('mp_exam', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='测试id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=50),
               nullable=False,
               existing_comment='测试名称')
        batch_op.alter_column('tag',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=20),
               nullable=False,
               existing_comment='测试标签')
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='测试状态 0正常 -1停用',
               existing_comment='测试状态,0 正常 -1禁用',
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='创建时间')
        batch_op.create_index('index_id', ['id'], unique=False)
        batch_op.create_index('index_name', ['name'], unique=False)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_table_comment(
        existing_comment='测试表'
    )

    with op.batch_alter_table('mp_option', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='选项id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='问题id',
               existing_comment='所属问题id')
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=500),
               nullable=False,
               existing_comment='选项内容')
        batch_op.alter_column('is_right',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='选项是否正确 0错误 1正确',
               existing_comment='选项是否正确，0为错误，1为正确')
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='状态 0正常 -1停用',
               existing_comment='选项状态，0 为正常 -1禁用',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='创建时间')
        batch_op.create_index('index_id', ['id'], unique=False)
        batch_op.create_index('index_question_id', ['question_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='测试问题选项表'
    )

    with op.batch_alter_table('mp_question', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='问题id',
               existing_comment='主键id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(),
               comment='测试id',
               existing_comment='所属测试id',
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='问题类型 1为单选，2为多选 3为判断')
        batch_op.alter_column('type_name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=20),
               nullable=False,
               existing_comment='问题类型文本，对应type字段')
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='测试状态 0正常 -1禁用',
               existing_comment='问题状态，0为正常，-1为禁用',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('analysis',
               existing_type=mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'),
               type_=sa.String(length=500),
               nullable=False,
               existing_comment='问题解析')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间')
        batch_op.create_index('index_exam_id', ['exam_id'], unique=False)
        batch_op.create_index('index_id', ['id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='测试问题表'
    )

    with op.batch_alter_table('mp_user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=500),
               nullable=False,
               comment='用户名',
               existing_comment='账户名称')
        batch_op.alter_column('nick_name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=500),
               nullable=False,
               comment='用户昵称',
               existing_comment='昵称')
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=500),
               nullable=False,
               comment='用户密码',
               existing_comment='账户密码')
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=20),
               nullable=False,
               comment='用户手机号')
        batch_op.alter_column('wx_openid',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=500),
               nullable=False,
               comment='用户微信openid')
        batch_op.alter_column('wx_unionid',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=500),
               nullable=False,
               comment='用户微信unionid')
        batch_op.alter_column('head_url',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=500),
               nullable=False,
               comment='用户头像url')
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='用户年龄')
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=500),
               nullable=False,
               comment='用户地址')
        batch_op.alter_column('gender',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='用户性别,0为暂无 1为男，2为女',
               existing_comment='0为暂无，1为男 2为女')
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=500),
               nullable=False,
               comment='用户邮箱')
        batch_op.alter_column('login_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='登录次数')
        batch_op.alter_column('last_login_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='最后登录时间')
        batch_op.alter_column('is_admin',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='是否管理员,0为否，1为是',
               existing_comment='0为普通用户，1为管理员')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='创建时间')
        batch_op.create_index('index_id', ['id'], unique=False)
        batch_op.create_index('index_phone', ['phone'], unique=False)
        batch_op.create_unique_constraint(None, ['wx_unionid'])
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_unique_constraint(None, ['wx_openid'])

    with op.batch_alter_table('mp_user_exam', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户测试id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='用户id')
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='测试id')
        batch_op.alter_column('type',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='用户测试类型  0是顺序练习，1是模拟考试',
               existing_comment='测试类型（顺序练习0，模拟考试1）')
        batch_op.alter_column('type_name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=20),
               nullable=False,
               comment='用户测试类型名称',
               existing_comment='测试类型名称（顺序练习/模拟考试）')
        batch_op.alter_column('last_question_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='最后做的问题ID，用于记录用户最后做题的位置',
               existing_comment='最后做的问题ID')
        batch_op.alter_column('correct_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='答对题目数',
               existing_comment='答对数量')
        batch_op.alter_column('error_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='答错题目数',
               existing_comment='答错数量')
        batch_op.alter_column('total_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='总题目数',
               existing_comment='题目总数量')
        batch_op.alter_column('question_ids',
               existing_type=mysql.JSON(),
               nullable=False,
               comment='题目ID数组快照，例如：[1, 5, 12, 23, ...] ，不受后续题库变化影响',
               existing_comment='题目id快照')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='创建时间')
        batch_op.alter_column('finish_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment='测试完成时间')
        batch_op.create_index('index_exam_id', ['exam_id'], unique=False)
        batch_op.create_index('index_id', ['id'], unique=False)
        batch_op.create_index('index_user_id', ['user_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='用户测试记录表'
    )

    with op.batch_alter_table('mp_user_exam_option', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户选项id',
               existing_comment='主键id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='用户id')
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='测试id')
        batch_op.alter_column('user_exam_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='用户测试id',
               existing_comment='记录id')
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='问题id')
        batch_op.alter_column('question_type',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='问题类型')
        batch_op.alter_column('option_ids',
               existing_type=mysql.JSON(),
               nullable=False,
               comment='选项id数组，无论单选多选都是列表。例如：[1, 3, 5, ...]',
               existing_comment='选项id数组')
        batch_op.alter_column('is_correct',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='是否答对 答对1 答错0')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间')
        batch_op.create_index('index_exam_id', ['exam_id'], unique=False)
        batch_op.create_index('index_id', ['id'], unique=False)
        batch_op.create_index('index_user_exam_id', ['user_exam_id'], unique=False)
        batch_op.create_index('index_user_id', ['user_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='用户选项记录表'
    )

    with op.batch_alter_table('mp_user_question_ebbinghaus_track', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户选项id',
               existing_comment='用户题目艾宾浩斯轨迹表id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               comment='问题id',
               existing_comment='题目id',
               existing_nullable=False)
        batch_op.alter_column('question_type',
               existing_type=mysql.INTEGER(),
               nullable=False,
               comment='问题类型',
               existing_comment='题目类型，单选多选等')
        batch_op.alter_column('correct_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='做对次数')
        batch_op.alter_column('error_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='做错次数')
        batch_op.alter_column('total_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='总做题次数')
        batch_op.alter_column('last_answer_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False,
               comment='最后一次答题时间',
               existing_comment='最后答题时间')
        batch_op.alter_column('next_review_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               comment='下一次复习的时间',
               existing_comment='下一次复习时间',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='题目做题状态：待复习0 已巩固1',
               existing_comment='当前题目复习状态：待复习0  已巩固1',
               existing_nullable=False)
        batch_op.alter_column('cycle_index',
               existing_type=mysql.INTEGER(),
               comment='艾宾浩斯记忆周期索引，初始索引为0，记忆周期是[1,3,7,14,30]。-1表示已巩固',
               existing_comment='复习周期索引，初始索引为0，复习周期是[0,1,3,7,14,30]。-1表示已巩固',
               existing_nullable=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间')
        batch_op.create_index('index_id', ['id'], unique=False)
        batch_op.create_index('index_next_review_time', ['next_review_time'], unique=False)
        batch_op.create_index('index_question_id', ['question_id'], unique=False)
        batch_op.create_index('index_status', ['status'], unique=False)
        batch_op.create_index('index_user_id', ['user_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='用户题目艾宾浩斯轨迹表'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mp_user_question_ebbinghaus_track', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户题目艾宾浩斯轨迹表',
        existing_comment=None
    )
        batch_op.drop_index('index_user_id')
        batch_op.drop_index('index_status')
        batch_op.drop_index('index_question_id')
        batch_op.drop_index('index_next_review_time')
        batch_op.drop_index('index_id')
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间')
        batch_op.alter_column('cycle_index',
               existing_type=mysql.INTEGER(),
               comment='复习周期索引，初始索引为0，复习周期是[0,1,3,7,14,30]。-1表示已巩固',
               existing_comment='艾宾浩斯记忆周期索引，初始索引为0，记忆周期是[1,3,7,14,30]。-1表示已巩固',
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='当前题目复习状态：待复习0  已巩固1',
               existing_comment='题目做题状态：待复习0 已巩固1',
               existing_nullable=False)
        batch_op.alter_column('next_review_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               comment='下一次复习时间',
               existing_comment='下一次复习的时间',
               existing_nullable=False)
        batch_op.alter_column('last_answer_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True,
               comment='最后答题时间',
               existing_comment='最后一次答题时间')
        batch_op.alter_column('total_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='总做题次数')
        batch_op.alter_column('error_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='做错次数')
        batch_op.alter_column('correct_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='做对次数')
        batch_op.alter_column('question_type',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='题目类型，单选多选等',
               existing_comment='问题类型')
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               comment='题目id',
               existing_comment='问题id',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户题目艾宾浩斯轨迹表id',
               existing_comment='用户选项id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('mp_user_exam_option', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户选项记录表',
        existing_comment=None
    )
        batch_op.drop_index('index_user_id')
        batch_op.drop_index('index_user_exam_id')
        batch_op.drop_index('index_id')
        batch_op.drop_index('index_exam_id')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间')
        batch_op.alter_column('is_correct',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='是否答对 答对1 答错0')
        batch_op.alter_column('option_ids',
               existing_type=mysql.JSON(),
               nullable=True,
               comment='选项id数组',
               existing_comment='选项id数组，无论单选多选都是列表。例如：[1, 3, 5, ...]')
        batch_op.alter_column('question_type',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='问题类型')
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='问题id')
        batch_op.alter_column('user_exam_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='记录id',
               existing_comment='用户测试id')
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='测试id')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='用户id')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键id',
               existing_comment='用户选项id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('mp_user_exam', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户测试记录表',
        existing_comment=None
    )
        batch_op.drop_index('index_user_id')
        batch_op.drop_index('index_id')
        batch_op.drop_index('index_exam_id')
        batch_op.alter_column('finish_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='测试完成时间')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
        batch_op.alter_column('question_ids',
               existing_type=mysql.JSON(),
               nullable=True,
               comment='题目id快照',
               existing_comment='题目ID数组快照，例如：[1, 5, 12, 23, ...] ，不受后续题库变化影响')
        batch_op.alter_column('total_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='题目总数量',
               existing_comment='总题目数')
        batch_op.alter_column('error_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='答错数量',
               existing_comment='答错题目数')
        batch_op.alter_column('correct_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='答对数量',
               existing_comment='答对题目数')
        batch_op.alter_column('last_question_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='最后做的问题ID',
               existing_comment='最后做的问题ID，用于记录用户最后做题的位置')
        batch_op.alter_column('type_name',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=20),
               nullable=True,
               comment='测试类型名称（顺序练习/模拟考试）',
               existing_comment='用户测试类型名称')
        batch_op.alter_column('type',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='测试类型（顺序练习0，模拟考试1）',
               existing_comment='用户测试类型  0是顺序练习，1是模拟考试')
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='测试id')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='用户id')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户测试id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('mp_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('index_phone')
        batch_op.drop_index('index_id')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
        batch_op.alter_column('is_admin',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='0为普通用户，1为管理员',
               existing_comment='是否管理员,0为否，1为是')
        batch_op.alter_column('last_login_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='最后登录时间')
        batch_op.alter_column('login_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='登录次数')
        batch_op.alter_column('email',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='用户邮箱')
        batch_op.alter_column('gender',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='0为暂无，1为男 2为女',
               existing_comment='用户性别,0为暂无 1为男，2为女')
        batch_op.alter_column('address',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='用户地址')
        batch_op.alter_column('age',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='用户年龄')
        batch_op.alter_column('head_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='用户头像url')
        batch_op.alter_column('wx_unionid',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='用户微信unionid')
        batch_op.alter_column('wx_openid',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='用户微信openid')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='用户手机号')
        batch_op.alter_column('password',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment='账户密码',
               existing_comment='用户密码')
        batch_op.alter_column('nick_name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment='昵称',
               existing_comment='用户昵称')
        batch_op.alter_column('name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               comment='账户名称',
               existing_comment='用户名')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('mp_question', schema=None) as batch_op:
        batch_op.create_table_comment(
        '测试问题表',
        existing_comment=None
    )
        batch_op.drop_index('index_id')
        batch_op.drop_index('index_exam_id')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间')
        batch_op.alter_column('analysis',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(charset='utf8mb3', collation='utf8mb3_general_ci'),
               nullable=True,
               existing_comment='问题解析')
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='问题状态，0为正常，-1为禁用',
               existing_comment='测试状态 0正常 -1禁用',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               existing_comment='问题类型文本，对应type字段')
        batch_op.alter_column('type',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='问题类型 1为单选，2为多选 3为判断')
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(),
               comment='所属测试id',
               existing_comment='测试id',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='主键id',
               existing_comment='问题id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('mp_option', schema=None) as batch_op:
        batch_op.create_table_comment(
        '测试问题选项表',
        existing_comment=None
    )
        batch_op.drop_index('index_question_id')
        batch_op.drop_index('index_id')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='选项状态，0 为正常 -1禁用',
               existing_comment='状态 0正常 -1停用',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_right',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='选项是否正确，0为错误，1为正确',
               existing_comment='选项是否正确 0错误 1正确')
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=500),
               nullable=True,
               existing_comment='选项内容')
        batch_op.alter_column('question_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='所属问题id',
               existing_comment='问题id')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='选项id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('mp_exam', schema=None) as batch_op:
        batch_op.create_table_comment(
        '测试表',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('index_name')
        batch_op.drop_index('index_id')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               nullable=True,
               comment='测试状态,0 正常 -1禁用',
               existing_comment='测试状态 0正常 -1停用',
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('tag',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               existing_comment='测试标签')
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               nullable=True,
               existing_comment='测试名称')
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='测试id',
               existing_nullable=False,
               autoincrement=True)

    op.create_table('t_org',
    sa.Column('org_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='组织机构id'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='上级组织机构id'),
    sa.Column('org_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='组织机构名称'),
    sa.Column('org_path', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='组织机构路径'),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), server_default=sa.text("'0'"), nullable=False, comment='组织机构状态（0正常1禁用）'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('update_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('org_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('t_org', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('parentid'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('org_name'), ['org_name'], unique=True)

    op.create_table('t_user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='用户id'),
    sa.Column('org_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='组织机构id'),
    sa.Column('position_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='职位id'),
    sa.Column('user_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=False, comment='用户名'),
    sa.Column('pass_word', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=False, comment='密码'),
    sa.Column('gender', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=10), nullable=True, comment='性别0男1女'),
    sa.Column('birthday', sa.DATE(), nullable=True, comment='出生年月'),
    sa.Column('avatar', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True, comment='头像'),
    sa.Column('email', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255), nullable=True, comment='邮箱'),
    sa.Column('phone', mysql.VARCHAR(charset='utf16le', collation='utf16le_general_ci', length=255), nullable=True, comment='电话'),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=10), server_default=sa.text("'0'"), nullable=False, comment='账号状态0正常1禁用'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.Column('update_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('t_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_name'), ['user_name'], unique=True)

    op.create_table('t_user_product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='用户商品id'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户id'),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='商品id'),
    sa.Column('source_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=False, comment='获得方式'),
    sa.Column('source_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='来源ID（如订单ID）'),
    sa.Column('expire_time', mysql.DATETIME(), nullable=True, comment='过期时间，NULL表示永久有效'),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否有效'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['product_id'], ['t_product.id'], name=op.f('t_user_product_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['mp_user.id'], name=op.f('t_user_product_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('t_user_product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('index_user_product'), ['user_id', 'product_id'], unique=False)
        batch_op.create_index(batch_op.f('index_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('index_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('index_product_id'), ['product_id'], unique=False)

    op.create_table('t_menu',
    sa.Column('menu_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='菜单id'),
    sa.Column('menu_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='菜单名称'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='上级菜单id'),
    sa.Column('menu_path', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='菜单路径'),
    sa.Column('menu_page', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='菜单页面'),
    sa.Column('menu_type', mysql.INTEGER(), autoincrement=False, nullable=False, comment='菜单类型（0为目录，1为菜单）'),
    sa.Column('is_link', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='菜单是否是外部链接（0不是，1是）'),
    sa.Column('visible', mysql.INTEGER(), autoincrement=False, nullable=False, comment='菜单侧边栏可见（0为可见，1为不可见）'),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), server_default=sa.text("'0'"), nullable=False, comment='菜单状态（0为正常，1为禁用）'),
    sa.Column('icon', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='菜单图标'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('menu_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_episodes',
    sa.Column('episodes_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='剧集id'),
    sa.Column('media_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='媒体id'),
    sa.Column('episodes_number', mysql.INTEGER(), autoincrement=False, nullable=False, comment='剧集序号'),
    sa.Column('episodes_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='剧集名称'),
    sa.Column('episodes_url', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='剧集地址'),
    sa.PrimaryKeyConstraint('episodes_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_role',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='角色id'),
    sa.Column('role_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=15), nullable=False, comment='角色编码'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='上级角色id'),
    sa.Column('role_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='角色名称'),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), server_default=sa.text("'0'"), nullable=False, comment='角色状态（0正常1禁用）'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('t_role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('1'), ['role_name'], unique=True)

    op.create_table('t_role_menu',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='角色id'),
    sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='菜单id'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色-菜单表',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='角色-菜单表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_dict',
    sa.Column('dict_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='字典id'),
    sa.Column('dict_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='字典名称'),
    sa.Column('dict_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False, comment='字典编码'),
    sa.Column('dict_label', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100), nullable=False, comment='字典标签'),
    sa.Column('dict_value', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='字典值'),
    sa.Column('remark', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('dict_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_media_tag',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('media_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_user_role',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户id'),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='角色id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('t_position',
    sa.Column('position_id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='职位id'),
    sa.Column('position_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='职位名称'),
    sa.Column('position_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255), nullable=False, comment='职位编码'),
    sa.Column('status', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=10), server_default=sa.text("'0'"), nullable=False, comment='职位状态（0正常1禁用）'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('position_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('t_position', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('position-name'), ['position_name'], unique=True)

    # ### end Alembic commands ###
